apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: demo-configuration
spec:
  crossplane:
    version: ">=v1.14.0"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-nop
      version: ">=v0.4.0"
    - provider: xpkg.upbound.io/upbound/provider-family-gcp
      version: ">=v2.5.3"
    - provider: xpkg.upbound.io/overlock-network/provider-akash
      version: ">=v0.0.17"
    - function: xpkg.upbound.io/crossplane-contrib/function-environment-configs
      version: ">=v0.1.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      version: ">=v0.7.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      version: ">=v0.2.1"
